// <auto-generated />
using System;
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBase.Migrations
{
    [DbContext(typeof(MysqlDbContext))]
    partial class MysqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataBase.Models.AccountModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FirstLogonTime");

                    b.Property<bool>("IsDisable");

                    b.Property<DateTime>("LastLogonTime");

                    b.Property<string>("LogonError")
                        .HasMaxLength(100);

                    b.Property<int>("LogonErrorNum");

                    b.Property<int>("OemId");

                    b.Property<string>("Password")
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("OemId");

                    b.ToTable("account");
                });

            modelBuilder.Entity("DataBase.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Psw");

                    b.HasKey("Id");

                    b.ToTable("TestData");
                });

            modelBuilder.Entity("DataBase.Models.UserInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AccountId");

                    b.Property<string>("City")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("HeadImg")
                        .HasMaxLength(255);

                    b.Property<bool>("IsFakePhone");

                    b.Property<string>("Mail")
                        .HasMaxLength(50);

                    b.Property<string>("NickName")
                        .HasMaxLength(20);

                    b.Property<int>("OemId");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("Province")
                        .HasMaxLength(20);

                    b.Property<string>("QQ")
                        .HasMaxLength(50);

                    b.Property<string>("RealName")
                        .HasMaxLength(20);

                    b.Property<string>("Region")
                        .HasMaxLength(20);

                    b.Property<int>("Source");

                    b.Property<string>("Weixin")
                        .HasMaxLength(50);

                    b.Property<string>("Wid")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("userinfo");
                });
#pragma warning restore 612, 618
        }
    }
}
